const fs = require('fs');
let lines = fs.readFileSync('src/app/globals.css', 'utf8').split('\n');
lines = lines.slice(0, 1592);
lines.push('.btn:disabled, button:disabled, input:disabled, textarea:disabled, select:disabled {');
lines.push('  opacity: 0.6;');
lines.push('  cursor: not-allowed;');
lines.push('}');
lines.push('');
lines.push('.input-error .input-field {');
lines.push('  border-color: var(--color-error);');
lines.push('  border-width: 2px;');
lines.push('}');
lines.push('');
lines.push('.input-required::after {');
lines.push('  content: " (required)";');
lines.push('  font-size: 0.85em;');
lines.push('  opacity: 0.8;');
lines.push('}');
lines.push('');
lines.push('.product-card-title-link::after {');
lines.push('  content: "";');
lines.push('  position: absolute;');
lines.push('  inset: 0;');
lines.push('  z-index: 1;');
lines.push('}');
fs.writeFileSync('src/app/globals.css', lines.join('\n'));
